



#POST http://localhost:82/api/login
#content-type: application/json
#
#{
#  "username": "%%&72",
#  "password": "1234"
#}
#POST http://localhost:82/api/register
#content-type: application/json
#
#{
#  "username": "xijinping",
#  "password": "1234",
#  "email": "a@1.com"
#}